Ia/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('Ia.views',

	 url(r'^thrift/home/$', 'welcome'),

	 url(r'^thrift/admin/home/$', 'admindash'),
	 
	 url(r'^thrift/admin/user/$', 'adminuserguide'),



####Field agents*****************
url(r'^staff/merchant/$', 'regfieldagent'),
 url(r'^staff/merchant/mycos/$', 'mycos'),



##********************customers****************************
	 url(r'^thrift/newsub/$', 'subscribe_cus'),
	 url(r'^thrift/newsub/subscribe/$', 'gensave'),
	 url(r'^customer/customer/$', 'depositer'),
	 


##customers***********************************
 url(r'^customeria/list/$', 'cus_list'), 



#***********************Thrift********************
	 url(r'^thrift/addthrift/$', 'addthrift'),
	 url(r'^thrift/viewthrift/$', 'viewthrift'),
	 url(r'^thrift/changethrift/$', 'changethrift'),


	 url(r'^thrift/changethrift/change/$','thriftedit'),
	 


	 
	 url(r'^thrift/rolloverthrift/$', 'rolloverthrift'),
	 url(r'^thrift/thriftreport/$', 'thriftrep'),

	 url(r'^thrift/addthrift/account_type/$', 'account_type'),
	 url(r'^thrift/addthrift/account_history/$', 'account_history'),

	 url(r'^thrift/addthrift/account_statement_history/$', 'account_statement_history'),





	 url(r'^thrift/deposit/account_dep/$', 'account_dep'),



	 url(r'^thrift/addthrift/account_view/$', 'account_view'),
	 url(r'^thrift/addthrift/account_change/$', 'account_change'),
	 url(r'^thrift/edit/thrift/$', 'edit_thrift_popup'),


	 url(r'^thrift/changethrift/edit/$','safethriftedit'),

	 url(r'^thrift/addthrift/putthrift/$', 'putthrift'),
	 url(r'^thrift/addthrift/putinthrift/$', 'putinthrift'),



	 #*************** activity log********************

	 url(r'^thrift/log/$', 'log'),
	 url(r'^thrift/log/merchant_ajax/$', 'fillmerchant'),
	 
	 url(r'^thrift/log/autopostlog/$', 'fillmerchantb'),

	 url(r'^thrift/log/payouts/$', 'payouts'),

	 url(r'^thrift/log/payouts/merchant_ajax/$', 'fillmerchant'),

	 url(r'^thrift/log/payouts/autopostlog/$', 'fillmerchantb'),

	 

	 url(r'^thrift/log/approvals/$', 'logapprove'),
	 url(r'^thrift/log/approvals/merchant_ajax/$', 'fillmerchantappr'),
	 url(r'^thrift/log/approvals/autopostlog/$', 'showtrans'),


	 url(r'^thrift/log/dr/$', 'log7'),
	 url(r'^thrift/log/dr/merchant_ajax/$', 'fillmerchant7'),
	 url(r'^thrift/log/dr/autopostlog/$', 'fillmerchantb7'),

	 


	 #*************** pay request********************
	 url(r'^thrift/payrequest/$', 'payrequests'),
	 url(r'^findthrift//$', 'autocomplete'),
	 url(r'^thrift/history/$', 'history'),

	 url(r'^thrift/mystatement/$', 'statementtt'),

	 url(r'^thrift/addmythrift/$','addmythrift'),

	 
	 url(r'^thrift/requests/cashin/admin/$', 'admin_cashin'),
	 url(r'^thrift/requests/cashin/cashier/$', 'cashier_cashin'),
	 url(r'^thrift/requests/cashin/agent/$', 'agent_cashin'),
	 
	 url(r'^thrift/unremmitted/$', 'unremmitted'),

	 url(r'^thrift/unremmitted/fa/$', 'fa_unremmitted'),
	 
	url(r'^thrift/funding/getsource/$','source'),
     

 	 url(r'^thrift/cashout/$', 'cashout'),
     url(r'^thrift/cashout/admin/$', 'cashoutrequest'),
   	 url(r'^thrift/withdraw/account_withdraw/$', 'account_withdraw'),
     url(r'^thrift/cashout/cash/$', 'cashoutrequest_cash'),
 	url(r'^thrift/cashout/agent/$', 'cashoutrequest_to'),

	 #***********************8*Remittals***************	
	url(r'^thrift/remittals/$', 'individual'),
	 url(r'^thrift/seedit/$','seedit'),

	url(r'^thrift/requests/adminpayfund/canceloptions/$','canceloptions'),
	url(r'^thrift/requests/adminpayfund/withdraw/$','withdrawoptions'),
	 url(r'^thrift/reedit/$','reedit'),

 url(r'^thrift/approvalsmenu/delete/yes/$', 'approvalsmenuyes'),



	# url(r'^thrift/remittals/remit/$', 'remitcash'),
	url(r'^thrift/approvals/approvebulk/$', 'approvebulkcash'),

	# url(r'^thrift/remittals/individualremit/$', 'indremitcash'),
	url(r'^thrift/aprrovals/approvalsingletrans/$', 'approveone'),
	
	url(r'^thrift/report/$', 'report'),

	#******************Approvals****************
    url(r'^thrift/approvalsmenu/$', 'approvalsmenu'),
    url(r'^thrift/approvals/$', 'approvals'),
        url(r'^thrift/approvalsmenu/approvefund/$', 'approvecash'),
    url(r'^thrift/allapprovals/$', 'allapproval'),

	url(r'^thrift/approvals/approvereport/$','approvereport'),

	url(r'^thrift/approvalforindv/$','approveind'),
	url(r'^thrift/approvalsmenu/approvefundforcustomer/$','approveindividualcash'),

###***************************Payout***************
      url(r'^thrift/payouts/$', 'payout'),
       url(r'^thrift/requests/adminpayfund/$', 'adminpayfund'),
      url(r'^thrift/payoutreport/$', 'payoutreport'),

      url(r'^thrift/requests/adminpayfund/cancel/nos/$','cancelreq'),
      url(r'^thrift/payouts/adminwithdraw/yes/$','withdrawfunds'),





##****************General Reports***********************
      url(r'^thrift/reports/home/$', 'repome'),



 ###############****************##Vaults******************
      url(r'^thrift/reports/sales/merchant/$','merchantreport'),
      url(r'^thrift/reports/getmereport/$','getmereportajax'),
      url(r'^thrift/reports/getdatemereport/$','getmereportajaxdate'),



      url(r'^thrift/reports/sales/cashier/$','cashierreport'),



#####***********************profits*********************************
      url(r'^thrift/reports/sales/admn/$','adminreport'),
      url(r'^thrift/reports/getprofit/$','getprofit'),
      url(r'^thrift/reports/getdateprofit/$','getdateprofit'),




#####***********************withdrawals*********************************       
        # url(r'^thrift/reports/sales/withdrawwa/$','clientwithdraw'),
        url(r'^thrift/reports/getwithdraw/$','getwithdraw'),



        url(r'^thrift/reports/getdatewithdraw/$','getdatewithdraw'),




      		#******merchants*******
      url(r'^thrift/reports/getmerchants/$','getmerchantid'),
      url(r'^thrift/reports/getmyname/$','getmerchantname'),
      url(r'^thrift/reports/getmereport/$','getmereportajax'),


      #*****Cashier**************
      url(r'^thrift/reports/getcashid/$','getcashid'),
      url(r'^thrift/reports/getcashname/$','getcashname'),
       url(r'^thrift/reports/getcashreport/$','getcashreportajax'),

      #****Admin***************
      url(r'^thrift/reports/getadminid/$','getadminid'),
      url(r'^thrift/reports/getadminname/$','getadminname'),
      url(r'^thrift/reports/getadminreport/$','getadminreportajax'),
    
###*****************************MISC************************
	url(r'^thrift/misc/customers/$', 'customerslist'),
	# url(r'^thrift/misc/namesearch/$', 'namesearch'),
	url(r'^thrift/misc/switches/$', 'switches'),
	url(r'^thrift/misc/getstaff/$','getallstall'),
	url(r'^thrift/misc/getswitch/$','getbutton'),
	# url(r'^thrift/misc/showselect/$','openoption'),

	
	)

loans/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('loans.views',
	 url(r'^loans/home/$', 'welcome'),
	 url(r'^loans/elgibility/$','eligibility'),
	 url(r'^loans/elgibility/dec/$','eligibilityyes'),

	 ####Individual Loans***************8
	 url(r'^loans/book_loan/individual/$','bookloan_individual'),

	 #####group loans ...................###
	 url(r'^loans/book_loan/creategroup/$','bookloan_creategroup'),
	 url(r'^loans/book_loan/membership/$','bookloan_membership'),
	 url(r'^loans/book_loan/bookloan/$','bookloan_bookloan'),

####***********All Ajax 
	url(r'^loans/book_loan/getlocation/$','getlocation'),
	url(r'^loans/book_loan/getgroupcode/$','getgroupcode'),
	url(r'^loans/generate/groupcode/$','generategroupcode'),
	url(r'^loans/book_loan/getgroupmembers/$', 'getgroupmembers'),
	url(r'^loans/book_loan/getgroupmembers/box/$','getgroupmembersbox'),
	url(r'^loans/book_loan/getloandetails/$','bookloandetails'),

    url(r'^loans/book_loan/getgroupmembers/approval/$','getapproved_groupmembers'),

	url(r'^loans/approvals/getcustomerdetails/$','autopostname1'),

	url(r'^loans/book_loan/getloandetails/individual/$','bookloandetails_indv'),
	url(r'^loans/book_loan/getstandardloan/$','getstandardloan'),
	url(r'^loans/book_loan/getloanparameters/$','loanparameters'),
	url(r'^loans/book_loan/getloanparametersjtjfj/$','loan_para_meters'),

############approvals###############

	 url(r'^loans/approvals/$','loanapprovals'),
	 url(r'^loans/approvals/yes/$','yesapprovaloan'),
	 url(r'^loans/termination/$', 'loantermination'),


###***************REPAYMENT*******************
	 url(r'^loans/repayment/$','loanrepay'),
	 url(r'^loans/repayment/payin/$','paybackloan'),

	 url(r'^loans/view_transaction/$','loan_view_transaction'),
	 
	 ###***************loan performance*******************

	 url(r'^loans/loan_performance/$','view_loan_performance'),
	 # url(r'^loans/defaults/$','individual'),

	 ###Settings&**************************

	 url(r'^loans/settings/$','loan_setup'),
	 

	)

thriftplus/urls.py
from django.conf.urls import patterns, include, url
from sysadmin.views import *


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', index),
    url(r'^login/$', index),
    url(r'^login/user/$', login),
    url(r'^logout/$', logoutuser),
    url(r'^changepass/$', changepass),
    url(r'^switch/$', switchuser),
    url(r'^dashboard/$', dashboard),
    url(r'^home/$', dashboard_client),
    url(r'^dashboard/name_search_ajax/$', namesearch),
    url(r'^dashboard/search/details/$', cusdetailS),
    # Examples:

    url(r'^customer/', include('customer.urls')),
    url(r'^fts/', include('Ia.urls')),
    url(r'^vts/', include('Ib.urls')),
    url(r'^IIIa/', include('IIIa.urls')),
    url(r'^IIIb/', include('IIIb.urls')),
    url(r'^loans/', include('loans.urls')),
    url(r'^sms/', include('sms.urls')),
    url(r'^savings/', include('savings.urls')),
    url(r'^staff/', include('staff.urls')),
    url(r'^corperative/', include('corperative.urls')),
    url(r'^partner/', include('partner.urls')),
    url(r'^sysadmin/', include('sysadmin.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

loans/models.py
from django.db import models


from customer.models import *


class tblstandardloan(models.Model):
	staffrec=models.ForeignKey(tblSTAFF)
	branch=models.ForeignKey(tblBRANCH)
	from_week=models.CharField(max_length=20)
	rate=models.CharField(max_length=20)
	to_week=models.CharField(max_length=20)
	description=models.CharField(max_length=20)
	status=models.CharField(max_length=20)

	def __unicode__(self):
		return '%s %s %s'%(self.rate,self.description,self.from_week)


class tbleligibility(models.Model):
	staffrec=models.ForeignKey(tblSTAFF)
	branch=models.ForeignKey(tblBRANCH)
	wallet=models.CharField(max_length=20)
	status=models.CharField(max_length=20)


	def __unicode__(self):
		return '%s %s %s'%(self.status,self.wallet,self.branch)


class tblLOANGROUPS(models.Model):
	staffrec=models.ForeignKey(tblSTAFF)
	branch=models.ForeignKey(tblBRANCH)
	status=models.CharField(max_length=20)
	group=models.CharField(max_length=20)
	location=models.CharField(max_length=20)


	def __unicode__(self):
		return '%s %s %s'%(self.status,self.location,self.branch)

class tblLOANGROUPMEMBERSHIP(models.Model):
	staffrec=models.ForeignKey(tblSTAFF)
	group=models.ForeignKey(tblLOANGROUPS)
	customer=models.ForeignKey(tblCUSTOMER)


	def __unicode__(self):
		return '%s %s %s'%(self.group,self.customer,self.staffrec)




class tblloandetails(models.Model):
	branch=models.ForeignKey(tblBRANCH)
	customer=models.ForeignKey(tblCUSTOMER)
	date =models.CharField(max_length=20)
	staffrec=models.ForeignKey(tblSTAFF)
	package=models.ForeignKey(tblstandardloan)
	status=models.CharField(max_length=20)
	volume=models.CharField(max_length=20)
	thrift=models.CharField(max_length=20)
	group=models.ForeignKey(tblLOANGROUPS)

	def __unicode__(self):
		return '%s %s %s'%(self.branch,self.volume,self.package)


class tblloantransaction(models.Model):
	transaction_source=models.ForeignKey(tblloandetails)
	start_date=models.CharField(max_length=20)
	status=models.CharField(max_length=20)
	amount=models.CharField(max_length=20)
	# wallet=models.CharField(max_length=20)


	def __unicode__(self):
		return '%s %s %s'%(self.amount,self.start_date,self.status)

loans/forms.py
from django import forms
from loans.models import *





loan_type = ( 

	('---', '--------'),
	('Standard','Standard'), 
	('Custom','Custom'), 

	)



monthy = (('---','----'),('January','January'),('February','February'),('March','March'),('April', 'April'),
	('May','May'),('June','June'),('July','July'),('August', 'August'),('September','September'),
	('October','October'),('November', 'November'),('December','December'))


month = (('-','----'),(1,'January'),(2,'February'),(3,'March'),(4, 'April'),
	(5,'May'),(6,'June'),(7,'July'),(8, 'August'),(9,'September'),
	(10,'October'),(11, 'November'),(12,'December'))


class eligibilityform(forms.Form):
	wallet = forms.IntegerField(label = 'Wallet Address')
	amount = forms.IntegerField(label = 'Amount')



class creategroup(forms.Form):
	wallet = forms.IntegerField(label = 'Wallet Address')
	group_code = forms.CharField(label = "Group Code",max_length = 20,widget = forms.TextInput(attrs={'readonly':'readonly'}))
	location = forms.CharField(label='Location',max_length= 190)


class individualform(forms.Form):
	wallet = forms.IntegerField(label = 'Wallet Address')
	Type = forms.ChoiceField(label = 'Loan Type', choices=loan_type)


class membershipform(forms.Form):
	wallet = forms.IntegerField(label = 'Wallet Address')
	location = forms.ChoiceField(label = 'Location', choices = [(c.location, c.location) for c in tblLOANGROUPS.objects.all()])
	group_code = forms.ChoiceField(label = 'Group Code', choices=[(c.group, c.group) for c in tblLOANGROUPS.objects.all()])

class grouploanform(forms.Form):
	location = forms.ChoiceField(label = 'Location', choices = [(c.location, c.location) for c in tblLOANGROUPS.objects.all()])
	group_code = forms.ChoiceField(label = 'Group Code', choices=loan_type)
	members = forms.ChoiceField(label = 'Group Members', choices = [(c.customer.wallet, c.customer.wallet) for c in tblLOANGROUPMEMBERSHIP.objects.all()])
	Type = forms.ChoiceField(label = 'Loan Type', choices=loan_type)
	rate = forms.IntegerField(label = 'Interest Rate')
	duration = forms.IntegerField(label = 'Duration')
	volume = forms.IntegerField(label = 'Amount')
	

class loanpackages(forms.Form):
	package = forms.ChoiceField(label = 'Available Loan Packages', choices=[(c.description, c.description) for c in tblstandardloan.objects.all().order_by('id')])

class loanapproveform(forms.Form):
	wallet = forms.IntegerField(label = 'Wallet Address')

class approveloangroupform(forms.Form):
	location = forms.ChoiceField(label = 'Location', choices = [(c.location, c.location) for c in tblLOANGROUPS.objects.all()])
	group_code = forms.ChoiceField(label = 'Group Code', choices=loan_type)
	members = forms.ChoiceField(label = 'Group Members', choices = [(c.customer.wallet, c.customer.wallet) for c in tblLOANGROUPMEMBERSHIP.objects.all()])

loans/templates/loans/approveloan_success.html
{% extends 'loans/loanadminbase.html' %}
{% block content %}

{% load humanize %}

<div style="text-align:center;font-weight:bold">Approvals and Termination</div>
 
   <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center;">

        <td  style="background:blue;font-size:0.9em">
            <a href="/loans/loans/approvals/" style="color:white">Approval</a>
        </td>
        <td  >
            <a href="/loans/loans/termination/" style="color:red">Termination</a>
        </td>
    </tr>
</table>


<table style="margin-top:0%;margin-bottom:0%;font-size:0.8em" width="100%" class="table table-bordered" id="dataTables-example">
<div> your Loan has been approved successfully, pay {{customer.surname }}  {{customer.firstname }}  {{customer.othername }}  the sum of N{{sum|intcomma }}</div>

</table>



<script type="text/javascript" language="javascript">
window.history.pushState(null, "", window.location.href);
window.onpopstate = function () {
    window.history.pushState(null, "", window.location.href);
};

</script>
{% endblock %}

loans/templates/loans/bookeddetails.html
{% load humanize %}


{% if data %}


<table style="margin-top:01%;margin-bottom:0.9%;font-size:0.9em" width="100%" class="table table-bordered" id="dataTables-example">
            <thead style=";text-align:center;font-weight:bold">
                <tr >
                    <td colspan='4' style="background-color: #ccccc0;color:#000000;text-align:center;" >Booking Details</td>
                </tr>
            <tr >
                
                <td >Wallet</td>
                <td >Name</td>
                <td >Booking</td>
            </tr>
            </thead>

            <tbody style=";text-align:center">
            
                <tr >
                    <td>{{ data.customer.wallet }}</td>
                    <td>{{ data.customer.surname }}, {{ data.customer.firstname }}{{data.customer.othername }}</td>
                    <td style="color:green">{{ status }}</td>
                
                </tr>
          
            </tbody>
</table>


{% endif %}



<script>
        $(document).ready(function() {

         autopost510();
        
        });
    </script>


  <script type="text/javascript" language="javascript">
        function autopost510(){
            var state = $("#id_members").val() + ':'+ '{{user}}';
            // alert(state)
            var url = "/loans/loans/book_loan/getloanparametersjtjfj/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".box51").show();
                    $(".box51").html(html);

                }
            });
            return false;
        }
    </script>

loans/templates/loans/customloan.html
<div style ='color:gray'> Custom loans not available at the moment </div> 

loans/templates/loans/eligibility_outcome.html
{% extends 'loans/loanadminbase.html' %}
{% block content %}


<div style="text-align:center;font-weight:bold">Elgibility Test</div>


<!--    <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center;">

        <td  >
            <a href="/loans/loans/book_loan/creategroup/" style="color:red">Create Group</a>
        </td>
        <td  >
            <a href="/loans/loans/book_loan/membership/" style="color:red">Membership</a>
        </td>
       <td  style="background:blue;font-size:0.9em">
        <a href="/loans/loans/book_loan/bookloan/" style="color:white">Book Loan</a>
    </td>
    </tr>
</table> -->


<table style="margin-top:0%;margin-bottom:0%;font-size:0.8em" width="100%" class="table table-bordered" id="dataTables-example">
<div>  </div>
{{msg}}
</table>


{% endblock %}

loans/templates/loans/loanterminate.html
{% extends 'loans/loanadminbase.html' %}



{% block content %}


<div style="text-align:center;font-weight:bold">Approvals and Termination</div>
 
   <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center;">

        <td  >
            <a href="/loans/loans/approvals/" style="color:red">Approval</a>
        </td>
        <td style="background:blue;font-size:0.9em" >
            <a href="/loans/loans/termination/" style="color:white">Termination</a>
        </td>
    </tr>
</table>


<form action="" method="POST">


<table style="margin-top:01%;margin-bottom:0%;font-size:0.9em" width="100%" class="table table-bordered" id="dataTables-example">
    
        <tr >
            <td >{{ form.wallet.label_tag}}:</td><td> {{ form.wallet }}</td>
        </tr>
       
</table>
<table style="margin-top:0%;margin-bottom:0%;font-size:0.6em" width="100%" class="table table-bordered" id="dataTables-example">
      
    <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="Process Termination">

</table>

 </form>

  
   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_location").change(function () {
                getgroupcode();
            });
            $("#id_group_code").change(function () {
                getgroupmembers();
            });
            
            $("#id_Type").change(function () {
                autopost201();
            });
            $("#id_members").change(function () {
                autopost201();
            });
            getlocation();
        });
    </script>


    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;
        }
    </script>
    
{% endblock %}

loans/templates/loans/ngl.html
<table style="margin-top:01%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">


<td>{{msg}}</td>


</table>

loans/templates/loans/repayloan.html
{% extends 'loans/loanadminbase.html' %}
{% block content %}


<div style="text-align:center;font-weight:bold">Loan Repayment System</div>
 
   <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center;">

        <td style="background:blue;font-size:0.9em" >
            <a href="/loans/loans/repayment/" style="color:white">Deposit</a>
        </td>
        <td  >
            <a href="/loans/loans/view_transaction/" style="color:red">View Transaction</a>
        </td>
    </tr>
</table>


{{msg}}
<form action="" method="POST">

<table style="margin-top:01%;margin-bottom:0%;font-size:0.9em" width="100%" class="table table-bordered" id="dataTables-example">
    
        <tr >
            <td >{{ form.wallet.label_tag}}:</td><td> {{ form.wallet }}</td>
        </tr>
       
</table>
<table style="margin-top:0%;margin-bottom:0%;font-size:0.6em" width="100%" class="table table-bordered" id="dataTables-example">
      
    <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="Process Payment">

</table>

 </form>



   <script type="text/javascript" >
        $(document).ready(function() {           
            $("#id_wallet").focus(); 
           
        });
    </script>


     <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;
        }
    </script>
    
{% endblock %}

loans/templates/loans/view_performance.html
{% extends 'loans/loanadminbase.html' %}
{% block content %}


<div style="text-align:center;font-weight:bold">Loan Performance</div>
 



<form action="" method="POST">


<table style="margin-top:01%;margin-bottom:0%;font-size:0.9em" width="100%" class="table table-bordered" id="dataTables-example">
    
        <tr >
            <td >{{ form.wallet.label_tag}}:</td><td> {{ form.wallet }}</td>
        </tr>
       
</table>
<table style="margin-top:0%;margin-bottom:0%;font-size:0.6em" width="100%" class="table table-bordered" id="dataTables-example">
      
    <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="View Performance">

</table>

 </form>

  
   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_wallet").focus();
        });
    </script>


    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;
        }
    </script>
    
{% endblock %}

loans/templates/loans/view_transaction.html
{% extends 'loans/loanadminbase.html' %}
{% block content %}


<div style="text-align:center;font-weight:bold">Loan Repayment</div>
 
   <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center;">

        <td  >
            <a href="/loans/loans/repayment/" style="color:red">Deposit</a>
        </td>
        <td  style="background:blue;font-size:0.9em">
            <a href="/loans/loans/view_transaction/" style="color:white">View Transaction</a>
        </td>
    </tr>
</table>


<form action="" method="POST">


<table style="margin-top:01%;margin-bottom:0%;font-size:0.9em" width="100%" class="table table-bordered" id="dataTables-example">
    
        <tr >
            <td >{{ form.wallet.label_tag}}:</td><td> {{ form.wallet }}</td>
        </tr>
       
</table>
<table style="margin-top:0%;margin-bottom:0%;font-size:0.6em" width="100%" class="table table-bordered" id="dataTables-example">
      
    <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="Process Termination">

</table>

 </form>

  
   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_location").change(function () {
                getgroupcode();
            });
            $("#id_group_code").change(function () {
                getgroupmembers();
            });
            
            $("#id_Type").change(function () {
                autopost201();
            });
            $("#id_members").change(function () {
                autopost201();
            });
            getlocation();
        });
    </script>


    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;
        }
    </script>
    
{% endblock %}