Ia/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('Ia.views',

	 url(r'^thrift/home/$', 'welcome'),

	 url(r'^thrift/admin/home/$', 'admindash'),
	 
	 url(r'^thrift/admin/user/$', 'adminuserguide'),



####Field agents*****************
url(r'^staff/merchant/$', 'regfieldagent'),
 url(r'^staff/merchant/mycos/$', 'mycos'),



##********************customers****************************
	 url(r'^thrift/newsub/$', 'subscribe_cus'),
	 url(r'^thrift/newsub/subscribe/$', 'gensave'),
	 url(r'^customer/customer/$', 'depositer'),
	 


##customers***********************************
 url(r'^customeria/list/$', 'cus_list'), 



#***********************Thrift********************
	 url(r'^thrift/addthrift/$', 'addthrift'),
	 url(r'^thrift/viewthrift/$', 'viewthrift'),
	 url(r'^thrift/changethrift/$', 'changethrift'),


	 url(r'^thrift/changethrift/change/$','thriftedit'),
	 


	 
	 url(r'^thrift/rolloverthrift/$', 'rolloverthrift'),
	 url(r'^thrift/thriftreport/$', 'thriftrep'),

	 url(r'^thrift/addthrift/account_type/$', 'account_type'),
	 url(r'^thrift/addthrift/account_history/$', 'account_history'),

	 url(r'^thrift/addthrift/account_statement_history/$', 'account_statement_history'),





	 url(r'^thrift/deposit/account_dep/$', 'account_dep'),



	 url(r'^thrift/addthrift/account_view/$', 'account_view'),
	 url(r'^thrift/addthrift/account_change/$', 'account_change'),
	 url(r'^thrift/edit/thrift/$', 'edit_thrift_popup'),


	 url(r'^thrift/changethrift/edit/$','safethriftedit'),

	 url(r'^thrift/addthrift/putthrift/$', 'putthrift'),
	 url(r'^thrift/addthrift/putinthrift/$', 'putinthrift'),



	 #*************** activity log********************

	 url(r'^thrift/log/$', 'log'),
	 url(r'^thrift/log/merchant_ajax/$', 'fillmerchant'),
	 
	 url(r'^thrift/log/autopostlog/$', 'fillmerchantb'),

	 url(r'^thrift/log/payouts/$', 'payouts'),

	 url(r'^thrift/log/payouts/merchant_ajax/$', 'fillmerchant'),

	 url(r'^thrift/log/payouts/autopostlog/$', 'fillmerchantb'),

	 

	 url(r'^thrift/log/approvals/$', 'logapprove'),
	 url(r'^thrift/log/approvals/merchant_ajax/$', 'fillmerchantappr'),
	 url(r'^thrift/log/approvals/autopostlog/$', 'showtrans'),


	 url(r'^thrift/log/dr/$', 'log7'),
	 url(r'^thrift/log/dr/merchant_ajax/$', 'fillmerchant7'),
	 url(r'^thrift/log/dr/autopostlog/$', 'fillmerchantb7'),

	 


	 #*************** pay request********************
	 url(r'^thrift/payrequest/$', 'payrequests'),
	 url(r'^findthrift//$', 'autocomplete'),
	 url(r'^thrift/history/$', 'history'),

	 url(r'^thrift/mystatement/$', 'statementtt'),

	 url(r'^thrift/addmythrift/$','addmythrift'),

	 
	 url(r'^thrift/requests/cashin/admin/$', 'admin_cashin'),
	 url(r'^thrift/requests/cashin/cashier/$', 'cashier_cashin'),
	 url(r'^thrift/requests/cashin/agent/$', 'agent_cashin'),
	 
	 url(r'^thrift/unremmitted/$', 'unremmitted'),

	 url(r'^thrift/unremmitted/fa/$', 'fa_unremmitted'),
	 
	url(r'^thrift/funding/getsource/$','source'),
     

 	 url(r'^thrift/cashout/$', 'cashout'),
     url(r'^thrift/cashout/admin/$', 'cashoutrequest'),
   	 url(r'^thrift/withdraw/account_withdraw/$', 'account_withdraw'),
     url(r'^thrift/cashout/cash/$', 'cashoutrequest_cash'),
 	url(r'^thrift/cashout/agent/$', 'cashoutrequest_to'),

	 #***********************8*Remittals***************	
	url(r'^thrift/remittals/$', 'individual'),
	 url(r'^thrift/seedit/$','seedit'),

	url(r'^thrift/requests/adminpayfund/canceloptions/$','canceloptions'),
	url(r'^thrift/requests/adminpayfund/withdraw/$','withdrawoptions'),
	 url(r'^thrift/reedit/$','reedit'),

 url(r'^thrift/approvalsmenu/delete/yes/$', 'approvalsmenuyes'),



	# url(r'^thrift/remittals/remit/$', 'remitcash'),
	url(r'^thrift/approvals/approvebulk/$', 'approvebulkcash'),

	# url(r'^thrift/remittals/individualremit/$', 'indremitcash'),
	url(r'^thrift/aprrovals/approvalsingletrans/$', 'approveone'),
	
	url(r'^thrift/report/$', 'report'),

	#******************Approvals****************
    url(r'^thrift/approvalsmenu/$', 'approvalsmenu'),
    url(r'^thrift/approvals/$', 'approvals'),
        url(r'^thrift/approvalsmenu/approvefund/$', 'approvecash'),
    url(r'^thrift/allapprovals/$', 'allapproval'),

	url(r'^thrift/approvals/approvereport/$','approvereport'),

	url(r'^thrift/approvalforindv/$','approveind'),
	url(r'^thrift/approvalsmenu/approvefundforcustomer/$','approveindividualcash'),

###***************************Payout***************
      url(r'^thrift/payouts/$', 'payout'),
       url(r'^thrift/requests/adminpayfund/$', 'adminpayfund'),
      url(r'^thrift/payoutreport/$', 'payoutreport'),

      url(r'^thrift/requests/adminpayfund/cancel/nos/$','cancelreq'),
      url(r'^thrift/payouts/adminwithdraw/yes/$','withdrawfunds'),





##****************General Reports***********************
      url(r'^thrift/reports/home/$', 'repome'),



 ###############****************##Vaults******************
      url(r'^thrift/reports/sales/merchant/$','merchantreport'),
      url(r'^thrift/reports/getmereport/$','getmereportajax'),
      url(r'^thrift/reports/getdatemereport/$','getmereportajaxdate'),



      url(r'^thrift/reports/sales/cashier/$','cashierreport'),



#####***********************profits*********************************
      url(r'^thrift/reports/sales/admn/$','adminreport'),
      url(r'^thrift/reports/getprofit/$','getprofit'),
      url(r'^thrift/reports/getdateprofit/$','getdateprofit'),




#####***********************withdrawals*********************************       
        # url(r'^thrift/reports/sales/withdrawwa/$','clientwithdraw'),
        url(r'^thrift/reports/getwithdraw/$','getwithdraw'),



        url(r'^thrift/reports/getdatewithdraw/$','getdatewithdraw'),




      		#******merchants*******
      url(r'^thrift/reports/getmerchants/$','getmerchantid'),
      url(r'^thrift/reports/getmyname/$','getmerchantname'),
      url(r'^thrift/reports/getmereport/$','getmereportajax'),


      #*****Cashier**************
      url(r'^thrift/reports/getcashid/$','getcashid'),
      url(r'^thrift/reports/getcashname/$','getcashname'),
       url(r'^thrift/reports/getcashreport/$','getcashreportajax'),

      #****Admin***************
      url(r'^thrift/reports/getadminid/$','getadminid'),
      url(r'^thrift/reports/getadminname/$','getadminname'),
      url(r'^thrift/reports/getadminreport/$','getadminreportajax'),
    
###*****************************MISC************************
	url(r'^thrift/misc/customers/$', 'customerslist'),
	# url(r'^thrift/misc/namesearch/$', 'namesearch'),
	url(r'^thrift/misc/switches/$', 'switches'),
	url(r'^thrift/misc/getstaff/$','getallstall'),
	url(r'^thrift/misc/getswitch/$','getbutton'),
	# url(r'^thrift/misc/showselect/$','openoption'),

	
	)

sms/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('sms.views',

	#***********************Sms Subscription********************
	url(r'^daily_contribution/sms/well/$','well'),
	url(r'^daily_contribution/sms/$','sms_customer'),

	url(r'^daily_contribution/balance/$','sms_purchase'),
	url(r'^thrift/sms/register/customer/$', 'transactional'),
	url(r'^thrift/sms/sms_history/$', 'sms_history'),
	url(r'^daily_contribution/weeklysms/$', 'weeklysms'),
	url(r'^daily_contribution/monthlysms/$', 'monthlysms'),

	url(r'^daily_contribution/requests/buysms/$', 'buysms'),
	url(r'^daily_contribution/pay/unit/$', 'unit'),
	url(r'^daily_contribution/pay/sms/$', 'pay4sms'),
	)

thriftplus/urls.py
from django.conf.urls import patterns, include, url
from sysadmin.views import *


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', index),
    url(r'^login/$', index),
    url(r'^login/user/$', login),
    url(r'^logout/$', logoutuser),
    url(r'^changepass/$', changepass),
    url(r'^switch/$', switchuser),
    url(r'^dashboard/$', dashboard),
    url(r'^home/$', dashboard_client),
    url(r'^dashboard/name_search_ajax/$', namesearch),
    url(r'^dashboard/search/details/$', cusdetailS),
    # Examples:

    url(r'^customer/', include('customer.urls')),
    url(r'^fts/', include('Ia.urls')),
    url(r'^vts/', include('Ib.urls')),
    url(r'^IIIa/', include('IIIa.urls')),
    url(r'^IIIb/', include('IIIb.urls')),
    url(r'^loans/', include('loans.urls')),
    url(r'^sms/', include('sms.urls')),
    url(r'^savings/', include('savings.urls')),
    url(r'^staff/', include('staff.urls')),
    url(r'^corperative/', include('corperative.urls')),
    url(r'^partner/', include('partner.urls')),
    url(r'^sysadmin/', include('sysadmin.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

Ia/forms.py
from django import forms
from staff.models import *
from Ia.models import *



approved= (('---','----'),('Approved', 'Approved'), ('Not Approved','Not Approved'))


transapproved= (('---','----'),('Approvals', 'Approvals'), ('Payouts','Payouts'), ('All','End Of Day'))

status = (('---','----'),('Paid', 'Paid'), ('Pending','Pending'))

rrprt = (('---','----'),('daily', 'daily'), ('weekly','weekly'),('monthly','monthly'))

remitted = (('---','----'),('Remitted', 'Remitted'), ('Unremmitted','Unremmitted'), ('All','All'))



dep = (('-----','-----'),('Contribution', 'Contribution'), ('Withdrawal','Withdrawal'), ('All','End Of Day'))

eod = (('-----','-----'),('Contribution', 'Contribution'), ('Withdrawal','Withdrawal'), ('All','All'))
trans_report = (('-----','----'),('DR', 'Contribution Requests'), ('WR','Withdrawal Requests'),('All','End Of Day'))

log = (('-----','----'),('DR', 'Contribution Requests'), ('WR','Withdrawal Requests'))

types = (('Main', 'Main'), ('Commission','Commission'))

avalability = (('Avalable', 'Avalable'), ('Not Available','Not Available'))

reason = ( 

	('Available', 'Available'),
	('Withdrawn','Withdrawn'), 
	('A/M','A/M'), 
	('Loan','Loan')

	)



monthy = (('---','----'),('January','January'),('February','February'),('March','March'),('April', 'April'),
	('May','May'),('June','June'),('July','July'),('August', 'August'),('September','September'),
	('October','October'),('November', 'November'),('December','December'))


month = (('-','----'),(1,'January'),(2,'February'),(3,'March'),(4, 'April'),
	(5,'May'),(6,'June'),(7,'July'),(8, 'August'),(9,'September'),
	(10,'October'),(11, 'November'),(12,'December'))




apps = ( 
	('-----','-----'),

	('Daily Contribution', 'Daily Contribution'),
	('Loans','Loans'),
	)

week = (('-','----'),(1,'Sunday'),(2,'Monday'),(3,'Tuesday'),(4, 'Wednesday'),
	(5,'Thursday'),(6,'Friday'),(7,'Saturday'))



class createwalletform(forms.Form):
    surname = forms.CharField(label='Surname',max_length= 190)
    firstname = forms.CharField(label='Firstname',max_length= 190)
    othername = forms.CharField(label='Otherame',max_length= 190, required=False)
    phone = forms.IntegerField(label='Phone' ,required=False)
    address = forms.CharField(label='Address',max_length= 190)
    email = forms.EmailField(label='E-mail' ,required=False)
    photo = forms.ImageField(label='Passport' ,required=False)

    def __init__(self, *args, **kwargs):
        super(createwalletform, self).__init__(*args)
        self.fields['surname'].widget.attrs['class'] = 'loginTxtbox'


class viewwalletform(forms.Form):
	wallet = forms.IntegerField(label = 'Wallet Address')



class viewmerchantform(forms.Form):
	merchant = forms.IntegerField(label = 'Merchant ID')
	date = forms.CharField(label = "Transaction Date",max_length = 20,widget = forms.TextInput(attrs={'readonly':'readonly'}))


class viewallremittedform(forms.Form):
	status = forms.ChoiceField(label = 'Status' , choices=remitted)
	date = forms.CharField(label = "Transaction Date",max_length = 20,widget = forms.TextInput(attrs={'readonly':'readonly'}))


class depreportform(forms.Form):
	status = forms.ChoiceField(label = 'Status' , choices=dep)
	date = forms.CharField(label = "Transaction Date",max_length = 20,widget = forms.TextInput(attrs={'readonly':'readonly'}))



class viewtransform(forms.Form):
	status = forms.ChoiceField(label = 'Status' , choices=trans_report)
	date = forms.CharField(label = "Transaction Date",max_length = 20,widget = forms.TextInput(attrs={'readonly':'readonly'}))


class viewallapprovedform(forms.Form):
	status = forms.ChoiceField(label = 'Status' , choices=transapproved)
	date = forms.CharField(label = "Transaction Date",max_length = 20,widget = forms.TextInput(attrs={'readonly':'readonly'}))


class viewlogform(forms.Form):
	date = forms.CharField(label = "Transaction Date",max_length = 20)
	merchant = forms.ChoiceField(label='Merchant ID',choices = [(c.id, c.id) for c in tblIaMERCHANT.objects.all()])



class logform(forms.Form):
	status = forms.ChoiceField(label = 'Status' , choices=log)


class payoutform(forms.Form):
	status = forms.ChoiceField(label = 'Status' , choices=status)
	date = forms.CharField(label = "Transaction Date",max_length = 20,widget = forms.TextInput(attrs={'readonly':'readonly'}))


class thriftform(forms.Form):
	month = forms.ChoiceField(label = 'Month' , choices=month)
	thrift = forms.IntegerField(label = 'Thrift')
	wallet=forms.IntegerField(label='Wallet Address', required=False)

class kthriftform(forms.Form):
	month = forms.CharField(label = 'Month',required=False)
	thrift = forms.IntegerField(label = 'Thrift')
	wallet=forms.IntegerField(label='Wallet Address', required=False)



class remittalform(forms.Form):
	merchant = forms.IntegerField(label = 'Merchant ID')
	date = forms.CharField(label = "Transaction Date",max_length =10,widget = forms.TextInput(attrs={'readonly':'readonly'}))




class thriftamountform(forms.Form):
	amount = forms.IntegerField(label = 'Amount')
	thrift = forms.IntegerField(label = 'Thrift', required=False)
	wallet = forms.IntegerField(label = 'Wallet Address' ,required=False)
	month = forms.CharField(label = 'Month' ,required=False)


class unremitform(forms.Form):
	month = forms.ChoiceField(label = 'Month' , choices=month)
	status = forms.ChoiceField(label = 'Status' , choices=remitted)

class thrifthistory(forms.Form):
	month = forms.ChoiceField(label = 'Month' , choices=month)


class viewremallform(forms.Form):
	date = forms.CharField(label = "Transaction Date",max_length = 20,widget = forms.TextInput(attrs={'readonly':'readonly'}))


class withcashform(forms.Form):
	wallet = forms.IntegerField(label = 'Wallete Address')
	date = forms.CharField(label = "Transaction Date",max_length =10,widget = forms.TextInput(attrs={'readonly':'readonly'}))

class merchantreportform(forms.Form):
	ID = forms.ChoiceField(label = "Merchant's ID",choices = [(c.id, c.id) for c in tblIaMERCHANT.objects.all()])
	name = forms.ChoiceField(label ="Name",choices = [(c.surname, c.surname) for c in tblSTAFF.objects.all()])
	date = forms.CharField(label = 'Select Date',max_length =10,widget = forms.TextInput(attrs={'readonly':'readonly'}))
	rtype = forms.ChoiceField(label = 'Report Type', choices=rrprt)


class cashreportform(forms.Form):
	ID = forms.ChoiceField(label = "Cashier's ID")
	name = forms.ChoiceField(label ="Name")
	date = forms.CharField(label = 'Select Date',max_length =10,widget = forms.TextInput(attrs={'readonly':'readonly'}))
	rtype = forms.ChoiceField(label = 'Report Type', choices=rrprt)

class performanceform(forms.Form):

	date = forms.CharField(label = 'Period',max_length =10,required=False,widget = forms.TextInput(attrs={'readonly':'readonly','size':10}))
	to_date = forms.CharField(label = "To",max_length = 20, required=False, widget = forms.TextInput(attrs={'readonly':'readonly','size':10}))

class endofdayform(forms.Form):
	status = forms.ChoiceField(label = 'Status' , choices=eod)
	date = forms.CharField(label = 'Period',max_length =10,required=False,widget = forms.TextInput(attrs={'readonly':'readonly','size':10}))
	to_date = forms.CharField(label = "To",max_length = 20, required=False, widget = forms.TextInput(attrs={'readonly':'readonly','size':10}))



class trackform(forms.Form):

	from_date = forms.CharField(label = 'Period',max_length =10,required=False,widget = forms.TextInput(attrs={'readonly':'readonly','size':10}))
	to_date = forms.CharField(label = "To",max_length = 20, required=False, widget = forms.TextInput(attrs={'readonly':'readonly','size':10}))



class switchesform(forms.Form):
	merchant = forms.IntegerField(label = 'Current Merchant ID')


class adminreportform(forms.Form):
	ID = forms.ChoiceField(label = "Admin's ID")
	name = forms.ChoiceField(label ="Name")
	date = forms.CharField(label = 'Select Date',max_length =10,widget = forms.TextInput(attrs={'readonly':'readonly'}))
	rtype = forms.ChoiceField(label = 'Report Type', choices=rrprt)


class newswitchform(forms.Form):
	merchant = forms.ChoiceField(label ="Select New Merchant",choices = [(c.id, c.id) for c in tblSTAFF.objects.all()])




class fieldofficerfform(forms.Form):
	email = forms.EmailField(label = 'Staff Email')

sms/forms.py
from django import forms
# from staff.models import *




month = (('-','----'),(1,'January'),(2,'February'),(3,'March'),(4, 'April'),
	(5,'May'),(6,'June'),(7,'July'),(8, 'August'),(9,'September'),
	(10,'October'),(11, 'November'),(12,'December'))




apps = ( 
	('-----','-----'),

	('Daily Contribution', 'Daily Contribution'),
	('Loans','Loans'),
	)

week = (('-','----'),(1,'Sunday'),(2,'Monday'),(3,'Tuesday'),(4, 'Wednesday'),
	(5,'Thursday'),(6,'Friday'),(7,'Saturday'))





class smsform(forms.Form):
	app = forms.ChoiceField(label = "App Category",choices = apps )


class smsweeklyform(forms.Form):
	dow = forms.ChoiceField(label = "Day Of Week",choices = week )

sms/templates/sms/buy_sms.html
{% extends 'sms/base.html' %}
{% block content %}


<div style="text-align:center">SMS Menu</div>
   <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">
<div>{{msg}}</div>
    <tr style="text-align:center;">
      <td  >
          <a href="/sms/daily_contribution/sms/"  style="color:red"> Schedule SMS</a>
      </td>
        <td style="background:blue">
          <a href="/sms/daily_contribution/balance/"  style="color:white">Purchase SMS</a>
      </td>
              <td >
          <a href="/sms/daily_contribution/history/"  style="color:red">SMS History</a>
      </td>
    </tr>
</table>


<form action="" method="POST">
   <table style="margin-top:0%;margin-bottom:0%;font-size:0.8em" width="100%" class="table  table-bordered" id="dataTables-example">

           <tr >
               <td >{{ form.wallet.label_tag}}:</td><td> {{ form.wallet }}</td>
             </tr>

       </table>



<table style="margin-top:0%;margin-bottom:0%;font-size:0.8em" width="100%" class="table  table-bordered" id="dataTables-example">
  <tr>
       <td >
        <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="Check Balance">
      </td>
  </tr>
   </table>
       </form>


   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_wallet").focus();
  
        });
    </script>

{% endblock %}

sms/templates/sms/funding.html
<div style='text-align:center;color:red;margin-top:05%'>Funding details</div>
<table style="margin-top:0.4%;margin-bottom:0.2%" width="100%" class="table  table-bordered" id="dataTables-example">

<tr>
    <td style='font-weight:bold'>Funding</td>
      <td>
      <select id="id_funding_type" Onchange="ShowHideDiv()">
      <option value="-----">-----</option>
      <option id ='kash'>Cash</option>
      <option id ="DC">Daily Contribution</option>
      </select>
    </td>
</tr>

<tr >
   <td >{{ form.month.label_tag}}:</td><td> {{ form.month }}</td>
</tr>

  <tr>
      <td style='font-weight:bold'>Account Type</td>
      <td>
          <select name="account_type" id="id_account_type">
           <option value="-----">-----</option>
           <option value="Main account">Main account</option>
           <option value="Sub account">Sub account</option>
           </select>
       </td>
</tr>
</table>


  <script type="text/javascript" >
        $(document).ready(function() {            
            $("#id_funding_type").change(function () {
                autopostfffe();
            });
            $("#id_funding_type").focus()

            $("#id_month").change(function () {
                autopostfffe();
            });
            $("#id_account_type").change(function () {
                autopostfffe();
            });
                         
            autopostfffe();
        });
    </script>




    <script type="text/javascript" language="javascript">
        function autopostfffe(){

            var state = $("#id_funding_type").val() + ":" 
            + $("#id_month").val() + ":" 
            + $("#id_account_type").val()+ ":" 
            + "{{user}}" + ":" 
            + "{{amount}}"+ ":"
            + "{{unit}}"+ ":" 
            + $("#wallet").val() 
            ;

            // alert(state)
            var url = "/sms/daily_contribution/pay/sms/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".boxcashfund").show();
                    $(".boxcashfund").html(html);

                }
            });
            return false;
        }
    </script>

sms/templates/sms/monthly_end.html
<form action = '/sms/daily_contribution/monthlysms/' method = 'post'>

<table style="margin-top:0%;margin-bottom:0.5%  " width="100%" class="table  table-bordered" id="dataTables-example">
<div style='text-align:center'>Select Date of Delivery</div>



<tr>


<td>
  <label for="id_start" ><input type="radio" name="dateofdel" id="id_start" value='start' onclick="ShowHideDiv1()" >Start Of Month</>
  </label>
</td>

<td>
  <label for="id_mid">
  <input type="radio"   name="dateofdel" id="id_mid" value='mid' onclick="ShowHideDiv2()">Mid Month </>
  </label>
</td>


<td>
  <label for="id_end"  style='color:grey'>
    <input type="radio" Disabled name="dateofdel" id="id_end" value='end' onclick="ShowHideDiv3()">End Of Month </>
  </label>
</td>
  </tr> 
</table> 

<div style='color:grey'>{{msg}}</div>


<div id="dvPassport" style="display: none">
  <table width="100%" class="table  table-bordered" id="dataTables-example">
    <tr>
       <td ><input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="Process Request" id="txtPassportNumber"></td>
      </tr>
</table>
</div>


<input type="hidden" name="wallet" id="wallet"  readonly="readonly" value="{{ wallet }}" class ="loginTxtbox">

<input type="hidden" name="app" id="app"  readonly="readonly" value="{{ app }}" class ="loginTxtbox">

</form>

<script type="text/javascript">
    function ShowHideDiv1() {
        var chkYes = document.getElementById("chkYes");
        var dvPassport = document.getElementById("dvPassport");
        dvPassport.style.display = id_start.checked ? "block" : "none";
    }
</script>


<script type="text/javascript">
    function ShowHideDiv2() {
        var chkYes = document.getElementById("chkYes");
        var dvPassport = document.getElementById("dvPassport");
        dvPassport.style.display = id_mid.checked ? "block" : "none";
    }
</script>

<script type="text/javascript">
    function ShowHideDiv3() {
        var chkYes = document.getElementById("chkYes");
        var dvPassport = document.getElementById("dvPassport");
        dvPassport.style.display = id_end.checked ? "block" : "none";
    }
</script>

sms/templates/sms/sms.html
{% extends 'sms/base.html' %}
{% block content %}


<div style="text-align:center">SMS Menu</div>
   <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">
<div>{{msg}}</div>
    <tr style="text-align:center;">
      <td  style="background:blue">
          <a href="/sms/daily_contribution/sms/"  style="color:white">Schedule SMS</a>
      </td>
        <td >
          <a href="/sms/daily_contribution/balance/"  style="color:red">Purchase SMS</a>
      </td>
            <td >
          <a href="/sms/daily_contribution/history/"  style="color:red">SMS History</a>
      </td>
    </tr>
</table>

   <table style="margin-top:0%;margin-bottom:0%;font-size:0.8em" width="100%" class="table  table-bordered" id="dataTables-example">

        <form action="" method="POST">
          
           <tr >
               <td >{{ form.wallet.label_tag}}:</td><td> {{ form.wallet }}</td>
             </tr>   
       </table>



<table style="margin-top:0%;margin-bottom:0%;font-size:0.8em" width="100%" class="table  table-bordered" id="dataTables-example">
  <tr>
       <td >
        <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="Check Balance">
      </td>
  </tr>
   </table>
       </form>


   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_wallet").focus();
  
        });
    </script>

{% endblock %}

sms/templates/sms/submit.html
<table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">
    <tr>
       <td ><input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="Process Request"></td>
     </tr>
  </table>


<input readonly hidden name = 'month' type = 'number' value = '{{ month }}' >

  <input readonly hidden name = 'funding' type = 'text' value = '{{funding}}'>

<input readonly hidden name = 'account' type = 'text' value = '{{account}}' >


<input readonly hidden name = 'user' type = 'text' value = '{{user }}' >

  <input readonly hidden name = 'wallet' type = 'number' value = '{{wallet}}'>

<input readonly hidden name = 'amount' type = 'number' value = '{{amount}}' >

<input readonly hidden name = 'unit' type = 'number' value = '{{unit}}' >