Ia/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('Ia.views',

	 url(r'^thrift/home/$', 'welcome'),

	 url(r'^thrift/admin/home/$', 'admindash'),
	 
	 url(r'^thrift/admin/user/$', 'adminuserguide'),



####Field agents*****************
url(r'^staff/merchant/$', 'regfieldagent'),
 url(r'^staff/merchant/mycos/$', 'mycos'),



##********************customers****************************
	 url(r'^thrift/newsub/$', 'subscribe_cus'),
	 url(r'^thrift/newsub/subscribe/$', 'gensave'),
	 url(r'^customer/customer/$', 'depositer'),
	 


##customers***********************************
 url(r'^customeria/list/$', 'cus_list'), 



#***********************Thrift********************
	 url(r'^thrift/addthrift/$', 'addthrift'),
	 url(r'^thrift/viewthrift/$', 'viewthrift'),
	 url(r'^thrift/changethrift/$', 'changethrift'),


	 url(r'^thrift/changethrift/change/$','thriftedit'),
	 


	 
	 url(r'^thrift/rolloverthrift/$', 'rolloverthrift'),
	 url(r'^thrift/thriftreport/$', 'thriftrep'),

	 url(r'^thrift/addthrift/account_type/$', 'account_type'),
	 url(r'^thrift/addthrift/account_history/$', 'account_history'),

	 url(r'^thrift/addthrift/account_statement_history/$', 'account_statement_history'),





	 url(r'^thrift/deposit/account_dep/$', 'account_dep'),



	 url(r'^thrift/addthrift/account_view/$', 'account_view'),
	 url(r'^thrift/addthrift/account_change/$', 'account_change'),
	 url(r'^thrift/edit/thrift/$', 'edit_thrift_popup'),


	 url(r'^thrift/changethrift/edit/$','safethriftedit'),

	 url(r'^thrift/addthrift/putthrift/$', 'putthrift'),
	 url(r'^thrift/addthrift/putinthrift/$', 'putinthrift'),



	 #*************** activity log********************

	 url(r'^thrift/log/$', 'log'),
	 url(r'^thrift/log/merchant_ajax/$', 'fillmerchant'),
	 
	 url(r'^thrift/log/autopostlog/$', 'fillmerchantb'),

	 url(r'^thrift/log/payouts/$', 'payouts'),

	 url(r'^thrift/log/payouts/merchant_ajax/$', 'fillmerchant'),

	 url(r'^thrift/log/payouts/autopostlog/$', 'fillmerchantb'),

	 

	 url(r'^thrift/log/approvals/$', 'logapprove'),
	 url(r'^thrift/log/approvals/merchant_ajax/$', 'fillmerchantappr'),
	 url(r'^thrift/log/approvals/autopostlog/$', 'showtrans'),


	 url(r'^thrift/log/dr/$', 'log7'),
	 url(r'^thrift/log/dr/merchant_ajax/$', 'fillmerchant7'),
	 url(r'^thrift/log/dr/autopostlog/$', 'fillmerchantb7'),

	 


	 #*************** pay request********************
	 url(r'^thrift/payrequest/$', 'payrequests'),
	 url(r'^findthrift//$', 'autocomplete'),
	 url(r'^thrift/history/$', 'history'),

	 url(r'^thrift/mystatement/$', 'statementtt'),

	 url(r'^thrift/addmythrift/$','addmythrift'),

	 
	 url(r'^thrift/requests/cashin/admin/$', 'admin_cashin'),
	 url(r'^thrift/requests/cashin/cashier/$', 'cashier_cashin'),
	 url(r'^thrift/requests/cashin/agent/$', 'agent_cashin'),
	 
	 url(r'^thrift/unremmitted/$', 'unremmitted'),

	 url(r'^thrift/unremmitted/fa/$', 'fa_unremmitted'),
	 
	url(r'^thrift/funding/getsource/$','source'),
     

 	 url(r'^thrift/cashout/$', 'cashout'),
     url(r'^thrift/cashout/admin/$', 'cashoutrequest'),
   	 url(r'^thrift/withdraw/account_withdraw/$', 'account_withdraw'),
     url(r'^thrift/cashout/cash/$', 'cashoutrequest_cash'),
 	url(r'^thrift/cashout/agent/$', 'cashoutrequest_to'),

	 #***********************8*Remittals***************	
	url(r'^thrift/remittals/$', 'individual'),
	 url(r'^thrift/seedit/$','seedit'),

	url(r'^thrift/requests/adminpayfund/canceloptions/$','canceloptions'),
	url(r'^thrift/requests/adminpayfund/withdraw/$','withdrawoptions'),
	 url(r'^thrift/reedit/$','reedit'),

 url(r'^thrift/approvalsmenu/delete/yes/$', 'approvalsmenuyes'),



	# url(r'^thrift/remittals/remit/$', 'remitcash'),
	url(r'^thrift/approvals/approvebulk/$', 'approvebulkcash'),

	# url(r'^thrift/remittals/individualremit/$', 'indremitcash'),
	url(r'^thrift/aprrovals/approvalsingletrans/$', 'approveone'),
	
	url(r'^thrift/report/$', 'report'),

	#******************Approvals****************
    url(r'^thrift/approvalsmenu/$', 'approvalsmenu'),
    url(r'^thrift/approvals/$', 'approvals'),
        url(r'^thrift/approvalsmenu/approvefund/$', 'approvecash'),
    url(r'^thrift/allapprovals/$', 'allapproval'),

	url(r'^thrift/approvals/approvereport/$','approvereport'),

	url(r'^thrift/approvalforindv/$','approveind'),
	url(r'^thrift/approvalsmenu/approvefundforcustomer/$','approveindividualcash'),

###***************************Payout***************
      url(r'^thrift/payouts/$', 'payout'),
       url(r'^thrift/requests/adminpayfund/$', 'adminpayfund'),
      url(r'^thrift/payoutreport/$', 'payoutreport'),

      url(r'^thrift/requests/adminpayfund/cancel/nos/$','cancelreq'),
      url(r'^thrift/payouts/adminwithdraw/yes/$','withdrawfunds'),





##****************General Reports***********************
      url(r'^thrift/reports/home/$', 'repome'),



 ###############****************##Vaults******************
      url(r'^thrift/reports/sales/merchant/$','merchantreport'),
      url(r'^thrift/reports/getmereport/$','getmereportajax'),
      url(r'^thrift/reports/getdatemereport/$','getmereportajaxdate'),



      url(r'^thrift/reports/sales/cashier/$','cashierreport'),



#####***********************profits*********************************
      url(r'^thrift/reports/sales/admn/$','adminreport'),
      url(r'^thrift/reports/getprofit/$','getprofit'),
      url(r'^thrift/reports/getdateprofit/$','getdateprofit'),




#####***********************withdrawals*********************************       
        # url(r'^thrift/reports/sales/withdrawwa/$','clientwithdraw'),
        url(r'^thrift/reports/getwithdraw/$','getwithdraw'),



        url(r'^thrift/reports/getdatewithdraw/$','getdatewithdraw'),




      		#******merchants*******
      url(r'^thrift/reports/getmerchants/$','getmerchantid'),
      url(r'^thrift/reports/getmyname/$','getmerchantname'),
      url(r'^thrift/reports/getmereport/$','getmereportajax'),


      #*****Cashier**************
      url(r'^thrift/reports/getcashid/$','getcashid'),
      url(r'^thrift/reports/getcashname/$','getcashname'),
       url(r'^thrift/reports/getcashreport/$','getcashreportajax'),

      #****Admin***************
      url(r'^thrift/reports/getadminid/$','getadminid'),
      url(r'^thrift/reports/getadminname/$','getadminname'),
      url(r'^thrift/reports/getadminreport/$','getadminreportajax'),
    
###*****************************MISC************************
	url(r'^thrift/misc/customers/$', 'customerslist'),
	# url(r'^thrift/misc/namesearch/$', 'namesearch'),
	url(r'^thrift/misc/switches/$', 'switches'),
	url(r'^thrift/misc/getstaff/$','getallstall'),
	url(r'^thrift/misc/getswitch/$','getbutton'),
	# url(r'^thrift/misc/showselect/$','openoption'),

	
	)

thriftplus/urls.py
from django.conf.urls import patterns, include, url
from sysadmin.views import *


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', index),
    url(r'^login/$', index),
    url(r'^login/user/$', login),
    url(r'^logout/$', logoutuser),
    url(r'^changepass/$', changepass),
    url(r'^switch/$', switchuser),
    url(r'^dashboard/$', dashboard),
    url(r'^home/$', dashboard_client),
    url(r'^dashboard/name_search_ajax/$', namesearch),
    url(r'^dashboard/search/details/$', cusdetailS),
    # Examples:

    url(r'^customer/', include('customer.urls')),
    url(r'^fts/', include('Ia.urls')),
    url(r'^vts/', include('Ib.urls')),
    url(r'^IIIa/', include('IIIa.urls')),
    url(r'^IIIb/', include('IIIb.urls')),
    url(r'^loans/', include('loans.urls')),
    url(r'^sms/', include('sms.urls')),
    url(r'^savings/', include('savings.urls')),
    url(r'^staff/', include('staff.urls')),
    url(r'^corperative/', include('corperative.urls')),
    url(r'^partner/', include('partner.urls')),
    url(r'^sysadmin/', include('sysadmin.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

Ia/models.py
from django.db import models

from staff.models import *

from customer.models import *




class tblIaMERCHANT(models.Model):
	branch=models.ForeignKey(tblBRANCH)
	staff=models.ForeignKey(tblSTAFF)
	status= models.BooleanField()
	code=models.IntegerField()
	thrift1a = models.BooleanField()


	def __unicode__(self):
		return '%s %s %s'%(self.staff,self.status,self.code)

#customers who subscribe to 1a service
class tblIaCUSTOMER(models.Model):
	branch=models.ForeignKey(tblBRANCH)
	merchant=models.ForeignKey(tblIaMERCHANT) #who registered me
	customer=models.ForeignKey(tblCUSTOMER)
	UX= models.BooleanField()
	status=models.BooleanField()
	online=models.BooleanField()
	code=models.IntegerField()
	sms=models.BooleanField()
	get_email=models.BooleanField()
	withdr_status=models.BooleanField()


	def __unicode__(self):
		return '%s %s %s'%(self.branch,self.status,self.code)




class tblIathrift(models.Model):
	customer=models.ForeignKey(tblIaCUSTOMER)
	branch=models.ForeignKey(tblBRANCH)
	month=models.CharField(max_length=20)
	thrift=models.IntegerField()
	code=models.IntegerField()
	year=models.CharField(max_length=20)
	account_type=models.CharField(max_length=20,default='Main account') #newly added


	def __unicode__(self):
		return '%s %s %s'%(self.account_type,self.month,self.code)


#C/Os accont for 1a where customers pay into
class tblIafieldagent(models.Model):
	status=models.CharField(max_length=30)
	branch=models.ForeignKey(tblBRANCH)
	merchant=models.ForeignKey(tblIaMERCHANT) #whose got the mone

	wallet_type=models.CharField(max_length=30)#main or referal

	amount=models.IntegerField() #amount recieved
	recdate=models.DateField() #date of recept
	customer=models.ForeignKey(tblIaCUSTOMER)
	number =models.IntegerField(max_length=40)
	
	code=models.CharField(max_length=30) #thrift related code
	account_type=models.CharField(max_length=20,default='Main account') #newly added
	transac_id=models.IntegerField(max_length=30) #transaction code

	def __unicode__(self):
		return '%s %s %s'%(self.recdate,self.amount,self.code)



#Cashiers accont for 1a where merchants  pay into ( for remittance)
class tblIaCashier(models.Model):
	branch=models.ForeignKey(tblBRANCH)
	customer=models.ForeignKey(tblIaCUSTOMER)

	merchant=models.ForeignKey(tblIaMERCHANT) #whose got the money

	remdate=models.DateField() #date of recept
	amount=models.IntegerField() #amount recieved
	number =models.CharField(max_length=40)

	wallet_type=models.CharField(max_length=30)#main or referal
	status=models.CharField(max_length=30)

	code=models.CharField(max_length=30) #transaction code
	remitted_by=models.CharField(max_length=50) #cashier detail
	account_type=models.CharField(max_length=20,default='Main account') #newly added


	def __unicode__(self):
		return '%s %s %s'%(self.remdate,self.amount,self.code)



#admin account for 1a for holding sales and approvals
class tblIamerchantBank(models.Model):
	branch=models.ForeignKey(tblBRANCH)
	# approved_date=models.DateField() #remittion date
	amount = models.IntegerField() #amount paid

	merchant=models.ForeignKey(tblIaMERCHANT) #if sales, admin. if approval, merchant

	customer=models.ForeignKey(tblIaCUSTOMER)
	recdate=models.DateField()  #date of record
	transdate=models.DateField()  #date of transaction


	number =models.CharField(max_length=40)
	code=models.IntegerField() #originates from thrift


	status= models.CharField(max_length=30)

	approved_by=models.CharField(max_length=50) #admin detail


	wallet_type=models.CharField(max_length=30,default='Main')
	account_type=models.CharField(max_length=20,default='Main account') #newly added


	transac_id = models.IntegerField() #transacttion id 



	def __unicode__(self):
		return '%s %s'%(self.recdate,self.amount)


#where all savings, withdrwals and service charges are kept
class tblIasavings_trans(models.Model):
	branch=models.ForeignKey(tblBRANCH)

	merchant=models.ForeignKey(tblIaMERCHANT) #who colected the money

	customer=models.ForeignKey(tblIaCUSTOMER) #whose money is it
	recdate=models.DateField() #recorddate
	transdate=models.DateField()  #date of transaction
	amount= models.IntegerField() #how much
	wallet_type=models.CharField(max_length=40,default='Main') #

	code=models.IntegerField(default=0) #originates from thrift

	number =models.CharField(max_length=40)
	description=models.CharField(max_length=40) #dr , cr
	status=models.CharField(max_length=40) #service charges, withdrawn,

	avalability=models.CharField(max_length=50) #use availability to manipulate withdrwal (if u got loan)

	account_type=models.CharField(max_length=20,default='Main account') #newly added

	transac_id = models.IntegerField() #transacttion id

	def __unicode__(self):
		return '%s %s %s'%(self.recdate,self.amount,self.wallet_type)



class tblIapayoutrequest(models.Model):
	customer=models.ForeignKey(tblIaCUSTOMER)
	merchant=models.ForeignKey(tblIaMERCHANT)
	branch=models.ForeignKey(tblBRANCH)
	account_type=models.CharField(max_length=40,default='Main')
	recdate=models.DateField() #cashin date from merchant
	status= models.CharField(max_length=20)
	amount=models.CharField(max_length=50)

	wallet_type=models.CharField(max_length=40,default='Main') #changed

	account_type=models.CharField(max_length=20,default='Main account') #newly added


	def __unicode__(self):
		return '%s %s %s'%(self.amount,self.wallet_type,self.customer)




class tblIapayoutrecord(models.Model):
	customer=models.ForeignKey(tblIaCUSTOMER)
	merchant=models.ForeignKey(tblIaMERCHANT)
	branch=models.ForeignKey(tblBRANCH)
	account_type=models.CharField(max_length=40,default='Main')
	recdate=models.DateField() #cashin date from merchant
	status= models.CharField(max_length=20)
	amount=models.CharField(max_length=50)
	wallet_type=models.CharField(max_length=40,default='Main') #changed

	account_type=models.CharField(max_length=20,default='Main account') #newly added


	def __unicode__(self):
		return '%s %s %s'%(self.amount,self.wallet_type,self.customer)

Ia/templates/Ia/adminpayoutsuccess.html
{% extends 'Ia/thriftbaseIa.html' %}

{% block content %}


<div class="card card-primary card-outline">
	<div class="card-header">
		<h5 class="m-0">CONGRATULATIONS!!!</h5>
		</div>
			<div class="card-body">
			<h6 class="card-title" > {{count}}  TRANSACTIONS COMPLETELY SUCCESSFULLY</h6>
			<p class="card-text"></p>
			<a href="/fts/thrift/payouts/" class="btn btn-primary">Continue</a>
	</div>

</div>


<script type="text/javascript" language="javascript">
window.history.pushState(null, "", window.location.href);
window.onpopstate = function () {
    window.history.pushState(null, "", window.location.href);
};

</script>

{% endblock %}

Ia/templates/Ia/approvalsreport.html
{% extends 'Ia/approval_base.html' %}
{% block content %}




<div style="text-align:center">Approvals Menu</div>
  
   <table style="margin-top:0%;margin-bottom:0% ;font-size:0.9em" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center;">
        <td >
            <a href="/fts/thrift/approvals/" style="color:red">Approval</a>
        </td>
        <td  >
            <a href="/fts/thrift/payouts/" style="color:red">Payouts</a>
        </td>  
       <td style="background:blue" >
        <a href="/fts/thrift/approvals/approvereport/" style="color:white">Log</a></td>
    </tr>
</table>


<table style="margin-top:0%;margin-bottom:0%;font-size:0.8em" width="100%" class="table  table-bordered" id="dataTables-example">


<form action="/fts/thrift/approvals/approvereport/" method="POST">



    <tr >
      <td >{{ form.status.label_tag}}:</td><td> {{ form.status }}</td>
    </tr>
    <tr >
      <td >{{ form.date.label_tag}}:</td><td> {{ form.date }}</td>
    </tr>
    <tr>
<!--     <td>Report Type:</td>
        <td>
        <div class="form-group">
        <div class="custom-control custom-switch">
        <input type="checkbox" name="checkbox" class="custom-control-input" id="customSwitch1">
        <label class="custom-control-label" for="customSwitch1">Monthly</label>
        </div>
        </div>
        </td>
    </tr> -->

    </table>
    <table style="margin-top:0%;margin-bottom:0%;font-size:0.8em" width="100%" class="table  table-bordered table-hover" id="dataTables-example">
    <td ><input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="View Report"></td>
</form>
</table>

    <script type="text/javascript" language="javascript">
        $(document).ready(function() {
            var pickerOpts = {
                // appendText: "yy/mm/dd",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"dd/mm/yy"
            };
            $("#id_date").datepicker(pickerOpts);
            //alert("welcome");
            $("#id_status").focus();
            autocomplete();
        });
    </script>
{% endblock %}

Ia/templates/Ia/approve_success.html
{% extends 'Ia/adminbase.html' %}

{% block content %}


{% load humanize %}

<div class="card card-primary card-outline">
  <div class="card-header">
    <h5 class="m-0" style='text-align:center'>CONGRATULATIONS!!!</h5>
    </div>
      <div class="card-body">
      <h6 class="card-title" >{{tot}}   TRANSACTION APPROVED SUCCESSFULLY</h6>
  </div>
</div>


<table style="margin-top:0.5%;margin-bottom:0.6%;text-align:center" width="100%" class="table  table-bordered" id="dataTables-example">

<tr >
    <td ><a href="/fts/thrift/remittals/">Remittals</a></td>

<td ><a href="/fts/thrift/approvals/">Approvals</a></td>
<td><a href="/fts/thrift/payouts/">Payments</a></td>

  <td><a href="/fts/thrift/home/" >Read guide</a></td>
</tr>
</table>



<script type="text/javascript" language="javascript">

window.history.pushState(null, "", window.location.href);
window.onpopstate = function () {
    window.history.pushState(null, "", window.location.href);
};

</script>

{% endblock %}

Ia/templates/Ia/changethrift_to.html
{% extends 'Ia/thriftbase_to.html' %}
{% block content %}


<div style="text-align:center">Thrift Menu</div>



<table style="margin-top:0%;margin-bottom:0%;font-size:0.9em;text-align:center" width="100%" class="table  table-bordered" >


    <tr>
        <td  >
            <a href="/fts/thrift/addthrift/" style="color:red">Add</a>
        </td>
        
        <td>
            <a href="/fts/thrift/viewthrift/" style="color:red">View</a>
        </td>
       <td style="background:blue" >
        <a href="/fts/thrift/changethrift/" style="color:white">Change</a></td>
        <td>
            <a href="/fts/thrift/rolloverthrift/" style="color:red">Rollover</a>
        </td>
        <td >
            <a href="/fts/thrift/thriftreport/" style="color:red">Log</a>
        </td>
    </tr>
</table>



<div>{{msg}}</div>
<form action="" method="POST">


<table style="margin-top:0.5%;margin-bottom:0.5%;font-size:0.7em" width="100%" class="table  table-bordered" >
           <tr >
               <td >{{ form.wallet.label_tag}}</td><td> {{ form.wallet }}</td>
             </tr>   
       </table>

 <table style="margin-top:0%;margin-bottom:02%" width="100%" class="table  table-bordered" >  

       <td >
        <input style="font-size:1em"  class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="View Thrift">
      </td>
      
</table>

 </form>


   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_wallet").focus();

            $("#id_klass").change(function () {
                 getsubject();
            });

        });
    </script>


{% endblock %}

Ia/templates/Ia/merchant_sales.html
{% extends 'Ia/contributionIabase_to.html' %}
{% block content %}

{% load humanize %}


<div style="text-align:center">Payments Menu</div>
   <table style="margin-top:0%;margin-bottom:0%;font-size:0.7em" width="100%" class="table  table-bordered">

    <tr style="text-align:center;">
        <td  >
            <a href="/fts/thrift/payrequest/"  style="color:red">Contribution Requests</a>
         <td  ><a href="/fts/thrift/cashout/" style="color:red">Withdrawal Requests</a></td>
        <td style="background:blue;font-size:0.9em">
            <a href="/fts/thrift/unremmitted/" style="color:white">Log</a>
        </td>
      
    </tr>
</table>

{% if thriftrec %}
             
  <table style="margin-top:0%;margin-bottom:02%;font-size:0.7em;text-align:center" width="100%" class="table  table-bordered">
     <thead >

      {% if status = 'All' %}

      <div style="text-align:center;margin-top:02%">   Summary of <span style='color:blue'>{{status}}</span> Transactions for   {{date}},  {{date2}}</div>

      {% else %}


      <div style="text-align:center;margin-top:02%"> Summary of <span style='color:blue'>{{status}}</span>  Transactions  for {{date}},  {{date2}}</div>

      {% endif %}

        <tr style="text-align:center;font-weight:bold">
           <td >S/N</td>
           <td > Customer</td>
             <td >Amount</td>
             <td >Status</td>
        </tr>
    </thead>                          
                            
    {% for student in thriftrec %}
        <tr style="ftext-align:center">
          <td >{{ forloop.counter }}.</td>
          <td >{{ student.customer.customer.surname }}, {{ student.customer.customer.firstname }}   {{ student.customer.customer.othername }}</td>
          <td >{{ student.amount|intcomma }}</td>

          {% if student.status = 'Received' %}
          <td style='color:red'>Not Yet Approved</td>
          {% else %}
          <td style='color:green'>{{student.status}}</td>
          {% endif %}
        </tr>
    {% endfor %}

        <tr style="text-align:center;font-weight:bold">
           <td style="font-weight:bold"></td>
            <td style="font-weight:bold">Total sales</td>
           <td > {{s|intcomma}}</td>
        </tr>

  {% else %}


  <div style='color:blue;text-align:center'>No transction record found </div>
  

</table>
{% endif %}



</table>

   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_amount").focus();
              getclass();

        });
    </script>


    <script type="text/javascript" language="javascript">
        function getclass(){
            var state = {{wallet}} ;
            // alert(state);
            var url = "/fts/thrift/getmonth/";
            var i = 0;
            var data='userid='+state;
            $("#id_klass").val('');
            $("#id_klass").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_klass").append(options);
                    }
                })
            }
        }

    </script>



    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;
        }
    </script>



{% endblock %}

Ia/templates/Ia/merchant_widr.html
{% extends 'Ia/contributionIabase_to.html' %}


{% block content %}

{% load humanize %}

<div style="text-align:center">Payments Menu</div>


   <table style="margin-top:0%;margin-bottom:0%;font-size:0.7em" width="100%" class="table  table-bordered">

    <tr style="text-align:center;">
        <td  >
            <a href="/fts/thrift/payrequest/"  style="color:red">Contribution</a>
         <td  ><a href="/fts/thrift/cashout/" style="color:red">Withdrawal</a></td>
        <td style="background:blue;font-size:0.9em">
            <a href="/fts/thrift/unremmitted/" style="color:white">Log</a>
        </td>
      
    </tr>
</table>

{% if thriftrec %}
             
   <table style="margin-top:0%;margin-bottom:02%;font-size:0.7em;text-align:center" width="100%" class="table  table-bordered">
     <thead >

      {% if status = 'All' %}

      <div style="text-align:center;margin-top:02%">   Summary of <span style='color:blue'>{{status}}</span> Transactions for   {{date}},  {{date2}}</div>

      {% else %}


      <div style="text-align:center;margin-top:02%"> Summary of <span style='color:blue'>{{status}}</span>  Transactions  for {{date}},  {{date2}}</div>

      {% endif %}

        <tr style="text-align:center;font-weight:bold">
           <td >S/N</td>
           <td > Customer</td>
             <td >Amount</td>
        </tr>
    </thead>                          
                            
    {% for student in thriftrec %}
        <tr style="ftext-align:center">
          <td >{{ forloop.counter }}.</td>
          <td >{{ student.customer.customer.surname }}, {{ student.customer.customer.firstname }}   {{ student.customer.customer.othername }}</td>
          <td >{{ student.amount|intcomma }}</td>
        </tr>
    {% endfor %}

        <tr style="text-align:center">
             <td style="font-weight:bold"></td>
             <td style="font-weight:bold">Total Withdrawal</td>
             <td >{{w|intcomma}}</td>
        </tr>

  {% else %}


  <div style='color:blue;text-align:center'>No transction record found </div>
  

</table>
{% endif %}



</table>

   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_amount").focus();
              getclass();

        });
    </script>


    <script type="text/javascript" language="javascript">
        function getclass(){
            var state = {{wallet}} ;
            // alert(state);
            var url = "/fts/thrift/getmonth/";
            var i = 0;
            var data='userid='+state;
            $("#id_klass").val('');
            $("#id_klass").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_klass").append(options);
                    }
                })
            }
        }

    </script>



    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;
        }
    </script>



{% endblock %}